# permissions for end users to view hostgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: k8s-hostgroup-viewer-role
rules:
- apiGroups:
  - k8s.cosmonic.io
  resources:
  - hostgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cosmonic.io
  resources:
  - hostgroups/status
  verbs:
  - get
