name: github-actions

on:
  pull_request:
    paths:
      - ".github/actions/*"
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  lint:
    permissions:
      statuses: write # to enable writing status checks
      contents: write # to fix linting issues
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Fetch all history for accurate diff in PRs

      - name: Lint Workflows and Actions
        id: lint
        uses: super-linter/super-linter/slim@5119dcd8011e92182ce8219d9e9efc82f16fddb6 #v8.0.0
        env:
          # Providing token to enable GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Super-Linter config files are stored in the `.github/linters` directory. See the docs
          # for the default name of each config file:
          # https://github.com/super-linter/super-linter/?tab=readme-ov-file#configure-super-linter
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true
