name: github-actions

on:
  pull_request:
    paths:
      - ".github/actions/*"
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  lint:
    permissions:
      statuses: write # to enable writing status checks
      contents: write # to fix linting issues
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0 # Fetch all history for accurate diff in PRs

      - name: Lint Workflows and Actions
        id: lint
        uses: super-linter/super-linter/slim@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 #v8.2.1
        env:
          # Providing token to enable GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Super-Linter config files are stored in the `.github/linters` directory. See the docs
          # for the default name of each config file:
          # https://github.com/super-linter/super-linter/?tab=readme-ov-file#configure-super-linter
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true
